import sys

def get_station_hash(s):
    b = s.encode('utf-8')
    length = len(b)
    val = length
    if length > 0:
        val |= (b[0] << 8)
        val |= (b[length // 2] << 16)
        val |= (b[length - 1] << 24)
        if length > 1:
            val |= (b[1] << 32)
            val |= (b[length - 2] << 40)
    return val

def find_perfect_multiplier(hashes, capacity):
    shift = 64 - (capacity - 1).bit_length()
    m = 11164934581231786391
    for _ in range(10000):
        collision = False
        seen = set()
        for h in hashes:
            idx = (h * m >> shift) & (capacity - 1)
            if idx in seen:
                collision = True
                break
            seen.add(idx)
        if not collision:
            return m
        m = (m * 6364136223846793005 + 1) & 0xFFFFFFFFFFFFFFFF
    return 11164934581231786391

def generate_mojo(input_file, output_file):
    with open(input_file, 'r') as f:
        stations = [line.strip() for line in f if line.strip()]
    
    hashes = [get_station_hash(s) for s in stations]
    multiplier = find_perfect_multiplier(hashes, 16384)
    
    with open(output_file, 'w') as f:
        f.write('# Automatically generated by scripts/generate_stations_mojo.py\n')
        f.write('comptime STATION_NAMES = (\n')
        for i, name in enumerate(stations):
            escaped_name = name.replace('"', '\\"')
            f.write(f'    "{escaped_name}"')
            if i < len(stations) - 1:
                f.write(',')
            f.write('\n')
        f.write(')\n\n')
        
        f.write('comptime STATION_HASHES = (\n')
        for i, h in enumerate(hashes):
            f.write(f'    {h}')
            if i < len(hashes) - 1:
                f.write(',')
            f.write('\n')
        f.write(')\n\n')
        
        f.write(f'alias PERFECT_MULTIPLIER: UInt64 = {multiplier}\n')

if __name__ == '__main__':
    generate_mojo('docs/stations413.txt', 'src/engine/stations_data.mojo')
    print("Generated src/engine/stations_data.mojo with STATION_HASHES and PERFECT_MULTIPLIER")
